### ISSUE TITLE
Жёлтый треугольник с восклицательным знаком [ошибка запуска]

### ISSUE THREAD

**Issue by Dramorian** [Kramar1337/ZenlessZoneZero-AHK-flex#1]
![image](https://github.com/Kramar1337/ZenlessZoneZero-AHK-flex/assets/6598192/84afb16a-9457-4d9f-b1d1-f57a037d83f4)
всё, что видно в трее, на хоткеи не реагирует

**Comment by Kramar1337** [comment]
прост у мя запущено много скриптов и это сделано чтобы не путаться. желтый треугольник это просто значок, он ничего не значит.
хоткеи не работают? хз, у меня все работает
заходишь в игру, начинается файт, нажимаешь "V" и ничего не происходит?

**Comment by Dramorian** [comment]
> прост у мя запущено много скриптов и это сделано чтобы не путаться. желтый треугольник это просто значок, он ничего не значит. хоткеи не работают? хз, у меня все работает заходишь в игру, начинается файт, нажимаешь "V" и ничего не происходит?

всё норм, я тупанул просто.
привык, что твои скрипты с тултипами по хоткею на нумпаде, вот и был в недоумении что не так, а оказывается тут сразу всё из-под коробки работает.
